### ISSUE TITLE
Chops off last character of each line

### ISSUE THREAD

**Issue by deftdawg** [GauthierEstJoly/paste-as-multiline-string#2]
Input:
```yaml
    restart: always
    networks:
          - some-network
networks:
  some-network:
    external: true
```

`Paste as a string` output:
```
"    restart: alway\n" +
"    networks\n" +
"          - some-networ\n" +
"networks\n" +
"  some-network\n" +
"    external: tru\n"
```

System:
```
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
